def printState(trials):
	mySting = ""
	if trials== 6:
		myString = "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
	elif trials == 5:
		myString  = "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
	elif trials == 4:
		myString  = "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|     /       "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
	elif trials == 3:
		myString  = "________      "
		myString  = myString + "\n" + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|     /|      "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
	elif trials == 2:
		myString = "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|     /|\     "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "|             "
	elif trials == 1:
		myString = "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|     /|\     "
		myString  = myString + '\n' + "|     /       "
		myString  = myString + '\n' + "|             "
	else:
		myString= "________      "
		myString  = myString + '\n' + "|      |      "
		myString  = myString + '\n' + "|      0      "
		myString  = myString + '\n' + "|     /|\     "
		myString  = myString + '\n' + "|     / \     "
		myString  = myString + '\n' + "|             "
		myString  = myString + '\n' + "The noose tightens around your neck, and you feel the"
		myString  = myString + '\n' + "sudden urge to urinate."
	print(myString)
